version: '3.8'

services:
    mosquitto:
        image: eclipse-mosquitto:2
        ports:
            - 1883:1883
            - 8883:8883
            - 9001:9001
        volumes:
            - /mosquitto/config:/mosquitto/config
            - /mosquitto/data:/mosquitto/data
        networks:
            - mosquitto
    estoque:
        image: pahomqtt
        command: python3 ./estoque_teste.py -n 10
        networks:
            - mosquitto
        depends_on:
            - mosquitto
    fabrica1:
        image: pahomqtt
        command: python3 ./fabrica_teste.py -i 1 -n 1 -t empurrada
        networks: 
            - mosquitto
        depends_on:
            - mosquitto
    fabrica2:
        image: pahomqtt
        command: python3 ./fabrica_teste.py -i 2 -n 1 -t puxada
        networks: 
            - mosquitto
        depends_on:
            - mosquitto
    linha:
        image: pahomqtt
        command: python3 ./linha_teste.py -i 0 -f 1
        networks:
            - mosquitto
        depends_on:
            - mosquitto
    linha2:
        image: pahomqtt
        command: python3 ./linha_teste.py -i 0 -f 2
        networks:
            - mosquitto
        depends_on:
            - mosquitto
    almoxarifado:
        image: pahomqtt
        command: python3 ./almoxarifado_teste.py
        networks:
            - mosquitto
        depends_on:
            - mosquitto
    fornecedor:
        image: pahomqtt
        command: python3 ./fornecedor_teste.py
        networks:
            - mosquitto
        depends_on:
            - mosquitto

networks:
    mosquitto:
        name: mosquitto
        driver: bridge